FROM python:3.11-slim 
 
ENV PYTHONDONTWRITEBYTECODE=1 
ENV PYTHONUNBUFFERED=1 
 
WORKDIR /app 
 
COPY requirements.txt /app/ 
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt 
 
COPY requirements.txt /app/ 
 
EXPOSE 8000 
 
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"] 